[package]
name = "autarco-scraper"
version = "0.1.0"
authors = ["Paul van Tilburg <paul@luon.net>"]
edition = "2018"

[dependencies]
color-eyre = "0.5.6"
lazy_static = "1.4.0"
thirtyfour_sync = "0.19.0"
