[package]
name = "autarco-scraper"
version = "0.1.0"
authors = ["Paul van Tilburg <paul@luon.net>"]
edition = "2018"

[dependencies]
color-eyre = "0.5.6"
lazy_static = "1.4.0"
serde = "1.0.116"
toml = "0.5.6"
thirtyfour = { version = "0.19.0", features = ["tokio-runtime"] }
tokio = { version = "0.2.22", features = ["process", "sync"] }

[dependencies.rocket]
git = "https://github.com/SergioBenitez/Rocket"
default-features = false

[dependencies.rocket_contrib]
git = "https://github.com/SergioBenitez/Rocket"
