version: '3'

services:
  server:
    image: autarco-scraper:latest
    build: .
    restart: unless-stopped
    ports:
      - 2356:8000
    # Use a `Rocket.toml` or configure the credentials using environment variables below
    volumes:
      - ./Rocket.toml:/autarco-scraper/Rocket.toml
    environment:
      ROCKET_LOG_LEVEL: normal  # Available levels are: off, debug, normal, critical
      # Put your My Autarco credentials below and uncomment them
      # ROCKET_USERNAME: foo@domain.tld
      # ROCKET_PASSWORD: secret
      # ROCKET_SITE_ID: abc123de
    shm_size: '2gb'
